### ISSUE TITLE
2.1.0 deprecated and missing function

### ISSUE THREAD

**Issue by majky358** [o5/grido#235]
grido/Components/Column
line:353 -> \Nette\Templating\Helpers::escapeHtml($value) /** deprecated */

grido/Grid
undefined callback() function

**Comment by o5** [comment]
Thanks for notice, but I have (maybe) a bad news for you. 

I just [locked](https://github.com/o5/grido/commit/e41ea5cf5cd8b424b8e244e6111665a3eaee30e4) `nette/nette` version to `>=2.0.0 <2.3.0`, so if you're using Nette version `>=2.3`, you currently have to use `@dev` version of `o5/grido`. Sorry for troubles!

**Comment by o5** [comment]
@majky358 Did you install Grido in your project through Composer?

**Comment by majky358** [comment]
Yes

**Comment by o5** [comment]
Curious! What version of Nette did you have or better could you attach your composer.json? 

I'm thinking that [commit](https://github.com/o5/grido/commit/e41ea5cf5cd8b424b8e244e6111665a3eaee30e4) was unnecessary, because `nette/nette` [requires](https://github.com/nette/nette/blob/v2.3/composer.json#L24) `nette/deprecated` and this package should resolve error reported by you.
