### ISSUE TITLE
PHP 7.2 - Cannot use 'Object' as class name as it is reserved

### ISSUE THREAD

**Issue by martinvenus** [o5/grido#295]
- bug report? yes
- feature request? no
- version: 2.1.2

### Description
 - PHP 7.2 uses "Object" as typehint (https://wiki.php.net/rfc/object-typehint).
 - Tested with docker image "php:7.2.0RC3-fpm".

**Comment by ondrakub** [comment]
@o5 hi, is there a chance for early support of PHP 7.2 ?

**Comment by Salamek** [comment]
@ondrakub looks like this project is dead, i'm migrating everything to https://github.com/ublaboo/datagrid

**Comment by o5** [comment]
@Salamek good luck

**Comment by o5** [comment]
@ondrakub PHP 7.2 is released but not all libraries are ready. For example xdebug is still in beta for 7.2, so I think 7.2 is not massively used for now.

**Comment by Salamek** [comment]
@o5 Or what is state of this project ?
Initialy i was thinking about porting this project to PHP 7.2, than i show 1year inactivity...

**Comment by ondrakub** [comment]
@o5 how grido depends on xdebug?
this project is inactive for one year, so I dont believe that support for 7.2 will come in next few weeks. I have forked this project in december and I modified it myself because I need it. I simply cannot use another grid.

But it's a shame because it has tens of thousands of downloads.

**Comment by peterpp** [comment]
I understand that maintaining open-source project requires author's free time. And if @o5 personally don't need updates, it's hard to allocate a time for it. However, it would be nice to manage at least pull requests. Community is here to help, but if I can see pending PR from 2015, I have no motivation to participate.

**Comment by Salamek** [comment]
BTW, i finished migration of all my active project to https://github.com/ublaboo/datagrid two days ago, and i can only recommend doing so:
* No hacky looking code needed to keep ~same functionality as with o5/grido
* Available filters makes more sence
* CSV export is much better
* API is similar to o5/grido from ~80% but feels more mature
* ...

**Comment by o5** [comment]
> BTW, i finished migration of all my active project to https://github.com/ublaboo/datagrid two days ago, and i can only recommend doing so

@Salamek I really appreciate you don't use Grido. Users like you are definitely unwelcome in any open source project.

**Comment by ondrakub** [comment]
@o5 oh, sorry, but a big project as the Grido is, you should have some responsibility. If you don't have time, which is understandable, you should  at least approve PR, leave the project to someone else or discontinue this project. Then no one would need to make a fork or recommend a different project here (at least in the first two cases)

**Comment by Salamek** [comment]
> I really appreciate you don't use Grido. Users like you are definitely unwelcome in any open source project.

@o5 Oh, you are so wrong...
Maintainers like you are definitely unwelcome in any open source project.

With this attitude and inactivity users will slowly abbandon your project.

Die well (grido) you was good servant but bad master...

PS: What is this behavior ?  I asked you about state of this project ^ when i was ready to port it to PHP 7.2 and do PR and you did not say anything, i needed some guarantee that my work wont go to /dev/null as all other 15! PRs in this repo. So get some balls to mark this project as abandoned or get someone to maintain it properly! I just suggested replacement to this project to help others to not enter a same "rabbit hole" since this project is obviously dying, it amazes me how you took this advice, you had two right options what to do and instead you started harassing me as a  "Bad OSS user" :smiley_cat: 

Peace

**Comment by o5** [comment]
Panove, uz toho mam opravdu dost :) Jde o to, ze opravdu **nikdo**, ani vy ani nikdo jiny, mne fakt nebude rikat co bych mel s projektem delat a co ne. Je mi totalne sumak, ze tento projekt vam brzdi nejake vase osobni projekty apod - to zijete v nejakem jinem svete nebo co? Dokazete si vubec predstavit co po me zadate? Pouzivejte si co chcete a doporucujte si co chcete, ale netahejte to do issue v tomhle projektu.
